modLoader = "javafml"
loaderVersion = "[0,)"

authors = "${author}"
license = "${license}"
issueTrackerURL = "${issuesURL}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
description = "${description}"
logoFile = "icon.png"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minimumMinecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[${minimumForgeVersion},)"
ordering = "NONE"
side = "BOTH"
