modLoader = "javafml"
loaderVersion = "[37,)"

authors = "chylex"
license = "MPL-2.0"
issueTrackerURL = "https://github.com/chylex/Better-Controls/issues"

[[mods]]
modId = "bettercontrols"
version = "${version}"
displayName = "${name}"
logoFile = "icon.png"
description = '''
Adds many powerful key bindings and options to control your movement.
The features complement vanilla mechanics without giving unfair advantages, so server use should be fine.
'''

[[dependencies.bettercontrols]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bettercontrols]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"
