modLoader = "javafml"
loaderVersion = "[37,)"

authors = "${author}"
license = "${license}"
issueTrackerURL = "${issuesURL}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
description = "${description}"
logoFile = "icon.png"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"
